PROMPT ARCHIVER 001 - metadata

CONNECT &&ACTIVE_ARCHIVER_SCHEMA/"&&ACTIVE_ARCHIVER_PASSWORD"@&&ACTIVE_ARCHIVER_CONNECT

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_TABLES
   WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
     AND SOURCE_TABLE_NAME IN
         ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC',
          'ORDERS_LIST_DATE_SRC', 'ORDERS_LIST_NUMBER_SRC', 'ORDERS_LIST_VARCHAR_SRC');

  IF l_count != 9 THEN
    RAISE_APPLICATION_ERROR(-20540, 'ARCHIVER expected 9 seeded table configs, got ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_TABLES
   WHERE SOURCE_DB_LINK IS NULL
      OR UPPER(TRIM(SOURCE_DB_LINK)) IN ('LOCAL', 'NONE');

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20541, 'ARCHIVER has invalid SOURCE_DB_LINK rows: ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_PARTITIONS
   WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
     AND SOURCE_TABLE_NAME IN
         ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC',
          'ORDERS_LIST_DATE_SRC', 'ORDERS_LIST_NUMBER_SRC', 'ORDERS_LIST_VARCHAR_SRC')
     AND SOURCE_PARTITION_NAME = 'P_ERROR';

  IF l_count != 14 THEN
    RAISE_APPLICATION_ERROR(-20542, 'ARCHIVER expected 14 seeded P_ERROR partition rows, got ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_TABLES
   WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
     AND PARTITION_METHOD = 'LIST';

  IF l_count != 3 THEN
    RAISE_APPLICATION_ERROR(-20544, 'ARCHIVER expected 3 LIST configs, got ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_TABLES
   WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
     AND IMPORT_EXPRESSION IS NOT NULL
     AND TRUNCATE_EXPRESSION IS NOT NULL;

  IF l_count != 9 THEN
    RAISE_APPLICATION_ERROR(-20545, 'ARCHIVER expected 9 expression configs, got ' || l_count);
  END IF;

  IF FN_ARCHIVER_EXPR_CALC('10, 11', NULL, '#', '10 IN (<partition_high_value>)', 'FLAG') != 'Y'
     OR FN_ARCHIVER_EXPR_CALC('''N'', ''S''', NULL, '''SHIPPED'', ''CLOSED''',
                     '''N'' IN (<partition_high_value>) AND ''CLOSED'' IN (<subpartition_high_value>)',
                     'FLAG') != 'Y' THEN
    RAISE_APPLICATION_ERROR(-20546, 'ARCHIVER expression evaluation failed');
  END IF;
END;
/

PROMPT ARCHIVER 001 completed
