PROMPT ARCHIVER 002 - AGENT DB link

CONNECT &&ACTIVE_ARCHIVER_SCHEMA/"&&ACTIVE_ARCHIVER_PASSWORD"@&&ACTIVE_ARCHIVER_CONNECT

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM USER_DB_LINKS
   WHERE DB_LINK = UPPER('&&ACTIVE_AGENT_LINK');

  IF l_count != 1 THEN
    RAISE_APPLICATION_ERROR(-20550, 'ARCHIVER AGENT DB link not found: &&ACTIVE_AGENT_LINK');
  END IF;

  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM dual@' || DBMS_ASSERT.SIMPLE_SQL_NAME('&&ACTIVE_AGENT_LINK')
    INTO l_count;

  EXECUTE IMMEDIATE
    'SELECT COUNT(*) FROM ' ||
    DBMS_ASSERT.SIMPLE_SQL_NAME('&&CLIENT1_SCHEMA') ||
    '.ORDERS_ARCH_SRC@' ||
    DBMS_ASSERT.SIMPLE_SQL_NAME('&&ACTIVE_AGENT_LINK') ||
    ' WHERE 1 = 0'
    INTO l_count;
END;
/

PROMPT ARCHIVER 002 completed
