PROMPT ARCHIVER 004 - quality and invalid objects

CONNECT &&ACTIVE_ARCHIVER_SCHEMA/"&&ACTIVE_ARCHIVER_PASSWORD"@&&ACTIVE_ARCHIVER_CONNECT

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_PARTITIONS
   WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
     AND SOURCE_TABLE_NAME IN ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC')
     AND ARCHIVE_STATUS = 'Y'
     AND (QUALITY_STATUS <> 'Y'
          OR NVL(SOURCE_ROW_COUNT, -1) <> NVL(TARGET_ROW_COUNT, -2));

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20570, 'ARCHIVER quality mismatch rows: ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_PARTITIONS
   WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
     AND SOURCE_TABLE_NAME IN ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC')
     AND ARCHIVE_STATUS = 'Y'
     AND QUALITY_STATUS = 'Y'
     AND TRUNCATE_STATUS = 'N'
     AND NVL(TARGET_ROW_COUNT, 0) > 0;

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20571, 'ARCHIVER truncate preview rows were not found');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM USER_OBJECTS
   WHERE STATUS <> 'VALID';

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20572, 'ARCHIVER invalid objects: ' || l_count);
  END IF;
END;
/

PROMPT ARCHIVER 004 completed
