PROMPT ARCHIVER 004 - quality and invalid objects

CONNECT &&ACTIVE_ARCHIVER_SCHEMA/"&&ACTIVE_ARCHIVER_PASSWORD"@&&ACTIVE_ARCHIVER_CONNECT

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_PARTITIONS
   WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
     AND SOURCE_TABLE_NAME IN
         ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC',
          'ORDERS_LIST_DATE_SRC', 'ORDERS_LIST_NUMBER_SRC', 'ORDERS_LIST_VARCHAR_SRC')
     AND ARCHIVE_STATUS = 'Y'
     AND (QUALITY_STATUS <> 'Y'
          OR NVL(SOURCE_ROW_COUNT, -1) <> NVL(TARGET_ROW_COUNT, -2));

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20570, 'ARCHIVER quality mismatch rows: ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_PARTITIONS
   WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
     AND SOURCE_TABLE_NAME IN
         ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC',
          'ORDERS_LIST_DATE_SRC', 'ORDERS_LIST_NUMBER_SRC', 'ORDERS_LIST_VARCHAR_SRC')
     AND ARCHIVE_STATUS = 'Y'
     AND QUALITY_STATUS = 'Y'
     AND TRUNCATE_STATUS = 'N'
     AND NVL(TARGET_ROW_COUNT, 0) > 0;

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20571, 'ARCHIVER truncate preview rows were not found');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM VW_ARCHIVER_TRUNCATE_PARTITIONS
   WHERE SOURCE_OWNER = UPPER('&&CLIENT1_SCHEMA')
     AND SOURCE_TABLE_NAME IN
         ('ORDERS_LIST_DATE_SRC', 'ORDERS_LIST_NUMBER_SRC', 'ORDERS_LIST_VARCHAR_SRC')
     AND TRUNCATE_FLAG = 'Y';

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20573, 'ARCHIVER LIST truncate expression candidates were not found');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM VW_ARCHIVER_TRUNCATE_PARTITIONS
   WHERE SOURCE_TABLE_NAME = 'ORDERS_DAILY_INT_SRC'
     AND TRUNCATE_FLAG = 'Y';

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20574, 'ARCHIVER executed a disabled truncate expression');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM VW_ARCHIVER_IMPORT_PARTITIONS
   WHERE IMPORT_FLAG LIKE 'ERROR:%';

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20575, 'ARCHIVER has invalid import expressions: ' || l_count);
  END IF;

  SELECT COUNT(DISTINCT r.run_type)
    INTO l_count
    FROM TBL_ARCHIVER_RUNS r
    JOIN TBL_ARCHIVER_PROCESS_LOG l
      ON l.mstr_log_id = r.mstr_log_id
   WHERE (r.run_type, r.run_id) IN
         (
           SELECT run_type, MAX(run_id)
             FROM TBL_ARCHIVER_RUNS
            WHERE run_type IN ('DISCOVER', 'ARCHIVE', 'QUALITY', 'TRUNCATE')
            GROUP BY run_type
         )
     AND DBMS_LOB.INSTR(l.log_json, '"type":"TABLE_CONTEXT"') > 0;

  IF l_count != 4 THEN
    RAISE_APPLICATION_ERROR(-20576, 'ARCHIVER expected TABLE_CONTEXT logs for 4 processes, got ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_PROCESS_LOG
   WHERE DBMS_LOB.INSTR(log_msg, 'RANGE / ORDER_DATE / DATE') > 0
     AND DBMS_LOB.INSTR(log_msg, '| SUBPARTITION | NONE') > 0;

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20577, 'ARCHIVER RANGE table context was not logged');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_ARCHIVER_PROCESS_LOG
   WHERE DBMS_LOB.INSTR(log_msg, 'LIST / REGION_CODE / VARCHAR2') > 0
     AND DBMS_LOB.INSTR(log_msg, 'LIST / STATUS_CODE / VARCHAR2') > 0;

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20578, 'ARCHIVER LIST-LIST table context was not logged');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM USER_OBJECTS
   WHERE STATUS <> 'VALID';

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20572, 'ARCHIVER invalid objects: ' || l_count);
  END IF;
END;
/

PROMPT ARCHIVER 004 completed
