SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Installing CLIENT1 test source objects

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_ARCH_SRC PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE ORDERS_ARCH_SRC
(
  ORDER_ID     NUMBER NOT NULL,
  CUSTOMER_ID  NUMBER NOT NULL,
  ORDER_DATE   DATE NOT NULL,
  STATUS_CODE  VARCHAR2(20) NOT NULL,
  AMOUNT       NUMBER(12,2) NOT NULL,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ORDERS_ARCH_SRC_PK PRIMARY KEY (ORDER_ID, ORDER_DATE)
)
PARTITION BY RANGE (ORDER_DATE)
(
  PARTITION P_ERROR VALUES LESS THAN
    (TO_DATE(' 1800-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')),
  PARTITION P202401 VALUES LESS THAN (DATE '2024-02-01'),
  PARTITION P202402 VALUES LESS THAN (DATE '2024-03-01'),
  PARTITION P202403 VALUES LESS THAN (DATE '2024-04-01'),
  PARTITION P202404 VALUES LESS THAN (DATE '2024-05-01'),
  PARTITION PMAX VALUES LESS THAN (MAXVALUE)
);

CREATE INDEX ORDERS_ARCH_SRC_LIX1
  ON ORDERS_ARCH_SRC (CUSTOMER_ID, ORDER_DATE)
  LOCAL;

CREATE INDEX ORDERS_ARCH_SRC_LIX2
  ON ORDERS_ARCH_SRC (STATUS_CODE, ORDER_DATE)
  LOCAL;

INSERT INTO ORDERS_ARCH_SRC (ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS_CODE, AMOUNT)
SELECT LEVEL,
       1000 + MOD(LEVEL, 17),
       DATE '2024-01-01' + MOD(LEVEL - 1, 115),
       CASE MOD(LEVEL, 4)
         WHEN 0 THEN 'NEW'
         WHEN 1 THEN 'PAID'
         WHEN 2 THEN 'SHIPPED'
         ELSE 'CLOSED'
       END,
       ROUND(10 + (LEVEL * 1.37), 2)
  FROM dual
CONNECT BY LEVEL <= 250;

COMMIT;

PROMPT CLIENT1 test source install completed
