SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@@config.local.sql

CONNECT &&ARCHIVER_SCHEMA/"&&ARCHIVER_PASSWORD"@&&ARCHIVER_SYS_CONNECT
@@code_root/create_db_link.sql &&ARCHIVER_AGENT_DB_LINK &&SOURCE_SYS_CONNECT &&AGENT_SCHEMA &&AGENT_PASSWORD
SET DEFINE OFF
@@install_archiver_code.sql

PROMPT Standalone ARCHIVER code installation completed
