SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@@config.local.sql

CONNECT &&REPLICA_SCHEMA/"&&REPLICA_PASSWORD"@&&REPLICA_SYS_CONNECT
@@code_root/create_db_link.sql &&REPLICA_ARCHIVER_DB_LINK &&ARCHIVER_SYS_CONNECT &&ARCHIVER_SCHEMA &&ARCHIVER_PASSWORD
CREATE OR REPLACE SYNONYM REPLICA_ARCHIVER_PARTITIONS_SRC
  FOR &&ARCHIVER_SCHEMA..TBL_ARCHIVER_PARTITIONS@&&REPLICA_ARCHIVER_DB_LINK;
SET DEFINE OFF
@@install_replica_code.sql

PROMPT Standalone REPLICA code installation completed
