SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@@config.local.sql

CONNECT &&AGENT_SCHEMA/"&&AGENT_PASSWORD"@&&SOURCE_SYS_CONNECT
SET DEFINE OFF
@@install_agent_code.sql

PROMPT Standalone AGENT code installation completed
