SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@@validate_config.sql

CONNECT &&SHARED_SCHEMA/"&&SHARED_PASSWORD"@&&SOURCE_SYS_CONNECT
SET DEFINE OFF
@@install_agent_code.sql

SET DEFINE ON
@@code_root/create_db_link.sql &&SHARED_AGENT_DB_LINK &&SOURCE_SYS_CONNECT &&SHARED_SCHEMA &&SHARED_PASSWORD
SET DEFINE OFF
@@install_archiver_code.sql

SET DEFINE ON
@@code_root/create_db_link.sql &&SHARED_ARCHIVER_DB_LINK &&SOURCE_SYS_CONNECT &&SHARED_SCHEMA &&SHARED_PASSWORD
CREATE OR REPLACE SYNONYM REPLICA_ARCHIVER_PARTITIONS_SRC
  FOR &&SHARED_SCHEMA..TBL_ARCHIVER_PARTITIONS@&&SHARED_ARCHIVER_DB_LINK;
SET DEFINE OFF
@@install_replica_code.sql

SET DEFINE ON
PROMPT SHARED code installation completed
