SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
BEGIN
  FOR r IN (SELECT sid, serial# FROM v$session
             WHERE username IN ('CLIENT1','CLIENT2','PARTMGR_AGENT','PARTMGR_ARCHIVER','PARTMGR_REPLICA','PARTMGR_SHARED')
               AND username IS NOT NULL)
  LOOP
    EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || r.sid || ',' || r.serial# || ''' IMMEDIATE';
  END LOOP;
END;
/
EXIT
