SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Granting CLIENT2 test source access to CAGENT1

GRANT SELECT ON ORDERS_ARCH_SRC TO CAGENT1;
GRANT DELETE ON ORDERS_ARCH_SRC TO CAGENT1;
GRANT ALTER ON ORDERS_ARCH_SRC TO CAGENT1;
GRANT SELECT ON ORDERS_ARCH_SRC TO CARCH;

PROMPT CLIENT2 grants completed
