SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Granting CLIENT2 daily interval-list test source access to CAGENT1

GRANT SELECT ON ORDERS_DAILY_INT_SRC TO CAGENT1;
GRANT DELETE ON ORDERS_DAILY_INT_SRC TO CAGENT1;
GRANT ALTER ON ORDERS_DAILY_INT_SRC TO CAGENT1;
GRANT SELECT ON ORDERS_DAILY_INT_SRC TO CARCH;

PROMPT CLIENT2 daily interval-list grants completed
