SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Installing CLIENT2 daily interval-list test source objects

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_DAILY_INT_SRC PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE ORDERS_DAILY_INT_SRC
(
  ORDER_ID     NUMBER NOT NULL,
  CUSTOMER_ID  NUMBER NOT NULL,
  ORDER_DATE   DATE NOT NULL,
  STATUS_CODE  VARCHAR2(20) NOT NULL,
  REGION_CODE  VARCHAR2(10) NOT NULL,
  AMOUNT       NUMBER(12,2) NOT NULL,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
PARTITION BY RANGE (ORDER_DATE)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
SUBPARTITION BY LIST (STATUS_CODE)
SUBPARTITION TEMPLATE
(
  SUBPARTITION SP_OPEN VALUES ('NEW', 'PAID'),
  SUBPARTITION SP_DONE VALUES ('SHIPPED', 'CLOSED')
)
(
  PARTITION P_ERROR VALUES LESS THAN
    (TO_DATE(' 1800-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')),
  PARTITION P20240501 VALUES LESS THAN (DATE '2024-05-02')
);

CREATE INDEX ORDERS_DAILY_INT_SRC_LIX1
  ON ORDERS_DAILY_INT_SRC (CUSTOMER_ID, ORDER_DATE)
  LOCAL;

CREATE INDEX ORDERS_DAILY_INT_SRC_LIX2
  ON ORDERS_DAILY_INT_SRC (REGION_CODE, ORDER_DATE)
  LOCAL;

INSERT INTO ORDERS_DAILY_INT_SRC
  (ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS_CODE, REGION_CODE, AMOUNT)
SELECT LEVEL,
       5000 + MOD(LEVEL, 19),
       DATE '2024-05-01' + MOD(LEVEL - 1, 4),
       CASE MOD(LEVEL, 4)
         WHEN 0 THEN 'NEW'
         WHEN 1 THEN 'PAID'
         WHEN 2 THEN 'SHIPPED'
         ELSE 'CLOSED'
       END,
       CASE MOD(LEVEL, 3)
         WHEN 0 THEN 'N'
         WHEN 1 THEN 'S'
         ELSE 'W'
       END,
       ROUND(50 + (LEVEL * 2.77), 2)
  FROM dual
CONNECT BY LEVEL <= 96;

COMMIT;

DECLARE
  l_new_name VARCHAR2(128);
BEGIN
  FOR r IN (
    SELECT partition_name,
           partition_position
      FROM all_tab_partitions p
     WHERE p.table_owner = 'CLIENT2'
       AND p.table_name = 'ORDERS_DAILY_INT_SRC'
       AND p.partition_name <> 'P_ERROR'
     ORDER BY p.partition_position
  ) LOOP
    l_new_name := 'P' || TO_CHAR(DATE '2024-05-01' + r.partition_position - 2, 'YYYYMMDD');

    IF r.partition_name <> l_new_name THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ORDERS_DAILY_INT_SRC RENAME PARTITION ' ||
                        r.partition_name || ' TO ' || l_new_name;
    END IF;
  END LOOP;
END;
/

PROMPT CLIENT2 daily interval-list test source install completed
