SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
  EXECUTE IMMEDIATE 'DROP DATABASE LINK ' || DBMS_ASSERT.SIMPLE_SQL_NAME(UPPER('&1'));
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2024 THEN
      RAISE;
    END IF;
END;
/

CREATE DATABASE LINK &1
  CONNECT TO &&APPLICATION_SCHEMA IDENTIFIED BY "&&APPLICATION_PASSWORD"
  USING '&2';

SELECT * FROM dual@&1;

CREATE OR REPLACE SYNONYM REPLICA_ARCHIVER_PARTITIONS_SRC
  FOR &&APPLICATION_SCHEMA..TBL_ARCHIVER_PARTITIONS@&1;
