SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Creating CREPL DB link to CARCH

BEGIN
  EXECUTE IMMEDIATE 'DROP DATABASE LINK CARCH_LOOPBACK_LINK';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2024 THEN
      RAISE;
    END IF;
END;
/

CREATE DATABASE LINK CARCH_LOOPBACK_LINK
  CONNECT TO CARCH IDENTIFIED BY "CarchDev2026_42"
  USING '//localhost:1521/FREEPDB1';

SELECT * FROM dual@CARCH_LOOPBACK_LINK;

PROMPT CREPL DB link to CARCH created
