SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Creating L3 synonyms to layer 2 metadata and data through DB link

CREATE OR REPLACE SYNONYM TW_ARCHIVE_TABLES FOR CARCH.TW_ARCHIVE_TABLES@CARCH_LOOPBACK_LINK;
CREATE OR REPLACE SYNONYM TW_ARCHIVE_PARTITIONS FOR CARCH.TW_ARCHIVE_PARTITIONS@CARCH_LOOPBACK_LINK;

CREATE OR REPLACE SYNONYM ORDERS_ARCH_SRC_L2 FOR CARCH.ORDERS_ARCH_SRC@CARCH_LOOPBACK_LINK;
CREATE OR REPLACE SYNONYM ORDERS_SUBPART_SRC_L2 FOR CARCH.ORDERS_SUBPART_SRC@CARCH_LOOPBACK_LINK;

PROMPT L3 synonyms to layer 2 through DB link created
