SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Creating L3 synonyms to layer 2 metadata and data

CREATE OR REPLACE SYNONYM TW_ARCHIVE_TABLES FOR CARCH.TW_ARCHIVE_TABLES;
CREATE OR REPLACE SYNONYM TW_ARCHIVE_PARTITIONS FOR CARCH.TW_ARCHIVE_PARTITIONS;

CREATE OR REPLACE SYNONYM ORDERS_ARCH_SRC_L2 FOR CARCH.ORDERS_ARCH_SRC;
CREATE OR REPLACE SYNONYM ORDERS_SUBPART_SRC_L2 FOR CARCH.ORDERS_SUBPART_SRC;

PROMPT L3 synonyms to layer 2 created
