SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@deploy/config/install_config.local.sql

PROMPT Connecting to configured REPLICA database
CONNECT &&APPLICATION_SCHEMA/"&&APPLICATION_PASSWORD"@&&REPLICA_CONNECT

SET DEFINE ON
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@deploy/layer3/create_archiver_source.sql &&REPLICA_ARCHIVER_DB_LINK &&ARCHIVER_CONNECT

SET DEFINE OFF
@deploy/layer3/install_layer3_replica.sql

PROMPT Standalone REPLICA component installation completed
