CREATE OR REPLACE TRIGGER TRG_ARCHIVE_TABLES_RETENTION_CALC
  BEFORE INSERT OR UPDATE OF RETENTION_RULE ON TW_ARCHIVE_TABLES
  FOR EACH ROW
DECLARE
  l_date DATE;
BEGIN
  l_date := FN_CALCULATE_RETENTION_RULE(:NEW.RETENTION_RULE);

  IF l_date IS NOT NULL THEN
    :NEW.RETENTION_CALC := 'correct: ' || TO_CHAR(l_date, 'YYYY-MM-DD');
  ELSE
    :NEW.RETENTION_CALC := 'wrong calculation of retention_rule';
  END IF;

  :NEW.UPDATED_AT := SYSDATE;
END;
/