create or replace TRIGGER TRG_ARCHIVE_TABLES_RETENTION_CALC
  BEFORE INSERT OR UPDATE OF RETENTION_RULE ON TW_ARCHIVE_TABLES
  FOR EACH ROW
DECLARE
  l_date DATE;
BEGIN
  l_date := FN_CALCULATE_RETENTION_RULE(:NEW.RETENTION_RULE);

  IF l_date IS NOT NULL THEN
    :NEW.RETENTION_CALC := 'CORRECT: returns DATE';
  ELSE
    :NEW.RETENTION_CALC := 'ERROR: returns NULL';
  END IF;
END;
/