SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
  EXECUTE IMMEDIATE 'DROP DATABASE LINK ' || DBMS_ASSERT.SIMPLE_SQL_NAME(UPPER('&1'));
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2024 THEN
      RAISE;
    END IF;
END;
/

CREATE DATABASE LINK &1
  CONNECT TO &3 IDENTIFIED BY "&4"
  USING '&2';

SELECT * FROM dual@&1;
