CREATE OR REPLACE TYPE ARCHIVE_PARTITION_INFO_OBJ AS OBJECT
(
  SCHEMA_NAME              VARCHAR2(128),
  TABLE_NAME               VARCHAR2(128),
  PARTITION_NAME           VARCHAR2(128),
  SUBPARTITION_NAME        VARCHAR2(128),
  PARTITION_HIGH_VALUE     VARCHAR2(4000),
  SUBPARTITION_HIGH_VALUE  VARCHAR2(4000),
  PARTITION_POSITION       NUMBER,
  SUBPARTITION_POSITION    NUMBER
);
/

