CREATE OR REPLACE PACKAGE PKG_ARCHIVE_DISCOVERY
AS
  PROCEDURE prc_discover
  (
    p_execute           IN VARCHAR2 DEFAULT 'N',
    p_target_owner      IN VARCHAR2 DEFAULT NULL,
    p_target_table_name IN VARCHAR2 DEFAULT NULL
  );
END PKG_ARCHIVE_DISCOVERY;
/
