CREATE TABLE TW_ARCHIVE_TABLES
(
  SOURCE_DB_LINK      VARCHAR2(128) NOT NULL,
  SOURCE_OWNER        VARCHAR2(128) NOT NULL,
  SOURCE_TABLE_NAME   VARCHAR2(128) NOT NULL,
  SOURCE_AGENT_SCHEMA VARCHAR2(128) NOT NULL,
  TARGET_OWNER        VARCHAR2(128) NOT NULL,
  TARGET_TABLE_NAME   VARCHAR2(128) NOT NULL,
  TRUNCATE_MODE       VARCHAR2(20)   DEFAULT 'TRUNCATE' NOT NULL,
  PARALLEL_DEGREE     NUMBER         DEFAULT 4 NOT NULL,
  TABLESPACE_NAME     VARCHAR2(128)  DEFAULT 'USERS' NOT NULL,
  LAST_BUSINESS_DATE  VARCHAR2(128)  DEFAULT 'dat.fn_eod' NOT NULL,
  DAYS_ONLINE         NUMBER         DEFAULT 30 NOT NULL,
  RETENTION_RULE      VARCHAR2(1000) DEFAULT 'select dat.fn_eod - 90 from dual' NOT NULL,
  RETENTION_CALC      VARCHAR2(500),
  PRESERVE_RULE       VARCHAR2(1000),
  PRESERVE_CALC       VARCHAR2(500),
  ENABLED_FLAG        VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  CREATED_AT          TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP,
  CONSTRAINT TW_ARCHIVE_TABLES_PK PRIMARY KEY
    (SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME),
  CONSTRAINT TW_ARCHIVE_TABLES_UK1 UNIQUE
    (TARGET_OWNER, TARGET_TABLE_NAME),
  CONSTRAINT TW_ARCHIVE_TABLES_CK1 CHECK (ENABLED_FLAG IN ('Y', 'N')),
  CONSTRAINT TW_ARCHIVE_TABLES_CK2 CHECK (TRUNCATE_MODE IN ('NONE', 'TRUNCATE'))
);
