-- Copy to distributed_topology.local.sql and configure ARCHIVER and REPLICA.
-- The same schema name may be used when components are on separate databases.

DEFINE DISTRIBUTED_ARCHIVER_CONNECT = archive-host:1521/archivepdb
DEFINE DISTRIBUTED_ARCHIVER_SCHEMA = PARTMGR
DEFINE DISTRIBUTED_ARCHIVER_PASSWORD = change_me
DEFINE DISTRIBUTED_ARCHIVER_ADMIN_USER = SYS
DEFINE DISTRIBUTED_ARCHIVER_ADMIN_PASSWORD = change_me
DEFINE DISTRIBUTED_ARCHIVER_ADMIN_ROLE = SYSDBA

DEFINE DISTRIBUTED_REPLICA_CONNECT = replica-host:1521/replicapdb
DEFINE DISTRIBUTED_REPLICA_SCHEMA = PARTMGR
DEFINE DISTRIBUTED_REPLICA_PASSWORD = change_me
DEFINE DISTRIBUTED_REPLICA_ARCHIVER_LINK = ARCHIVER_LINK
DEFINE DISTRIBUTED_REPLICA_ADMIN_USER = SYS
DEFINE DISTRIBUTED_REPLICA_ADMIN_PASSWORD = change_me
DEFINE DISTRIBUTED_REPLICA_ADMIN_ROLE = SYSDBA

DEFINE DISTRIBUTED_AGENT_MANIFEST = deploy/config/distributed_agents.local.sql
