DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM USER_TABLES
   WHERE TABLE_NAME = 'TBL_UTIL_REPORT_SQL';

  IF l_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE TBL_UTIL_REPORT_SQL
      (
        SQL_NAME   VARCHAR2(128) NOT NULL,
        SQL_CODE   CLOB NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP,
        CONSTRAINT TBL_UTIL_REPORT_SQL_PK PRIMARY KEY (SQL_NAME)
      )
      LOB (SQL_CODE) STORE AS SECUREFILE
    ]';
  END IF;
END;
/

MERGE INTO TBL_UTIL_REPORT_SQL t
USING (
  SELECT 'SQL_UTIL_SMOKE' sql_name,
         TO_CLOB(q'[SELECT USER AS schema_name, SYSDATE AS generated_at FROM dual]') sql_code
    FROM dual
) s
ON (t.SQL_NAME = s.SQL_NAME)
WHEN NOT MATCHED THEN
  INSERT (SQL_NAME, SQL_CODE)
  VALUES (s.SQL_NAME, s.SQL_CODE);

COMMIT;
