CREATE TABLE TBL_REPLICA_PARTITIONS
(
  SOURCE_DB_LINK            VARCHAR2(128) NOT NULL,
  SOURCE_OWNER              VARCHAR2(128) NOT NULL,
  SOURCE_TABLE_NAME         VARCHAR2(128) NOT NULL,
  TARGET_OWNER              VARCHAR2(128) NOT NULL,
  TARGET_TABLE_NAME         VARCHAR2(128) NOT NULL,
  ARCHIVE_UNIT_TYPE         VARCHAR2(20) NOT NULL,
  SOURCE_PARTITION_NAME     VARCHAR2(128) NOT NULL,
  SOURCE_SUBPARTITION_NAME  VARCHAR2(128) DEFAULT '#' NOT NULL,
  PARTITION_NAME            VARCHAR2(128) NOT NULL,
  SUBPARTITION_NAME         VARCHAR2(128) DEFAULT '#' NOT NULL,
  PARTITION_HIGH_VALUE      VARCHAR2(4000) NOT NULL,
  SUBPARTITION_HIGH_VALUE   VARCHAR2(4000) DEFAULT '#' NOT NULL,
  PREV_PARTITION_HIGH_VALUE VARCHAR2(4000),
  REPLICA_STATUS            VARCHAR2(1) DEFAULT 'N' NOT NULL,
  QUALITY_STATUS            VARCHAR2(1) DEFAULT 'N' NOT NULL,
  PURGE_STATUS              VARCHAR2(1) DEFAULT 'N' NOT NULL,
  SOURCE_ROW_COUNT          NUMBER,
  TARGET_ROW_COUNT          NUMBER,
  LAST_RUN_ID               NUMBER,
  ERROR_MESSAGE             VARCHAR2(4000),
  CREATED_AT                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT                TIMESTAMP,
  CONSTRAINT TBL_REPLICA_PARTITIONS_PK PRIMARY KEY
    (SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME, PARTITION_HIGH_VALUE, SUBPARTITION_HIGH_VALUE),
  CONSTRAINT TBL_REPLICA_PARTITIONS_FK1 FOREIGN KEY
    (SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME)
    REFERENCES TBL_REPLICA_TABLES
    (SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME),
  CONSTRAINT TBL_REPLICA_PARTITIONS_FK2 FOREIGN KEY (LAST_RUN_ID)
    REFERENCES TBL_REPLICA_RUNS (RUN_ID),
  CONSTRAINT TBL_REPLICA_PARTITIONS_UK1 UNIQUE
    (TARGET_OWNER, TARGET_TABLE_NAME, PARTITION_HIGH_VALUE, SUBPARTITION_HIGH_VALUE),
  CONSTRAINT TBL_REPLICA_PARTITIONS_CK1 CHECK
    (ARCHIVE_UNIT_TYPE IN ('PARTITION', 'SUBPARTITION')),
  CONSTRAINT TBL_REPLICA_PARTITIONS_CK2 CHECK
    (
      (ARCHIVE_UNIT_TYPE = 'PARTITION' AND SOURCE_SUBPARTITION_NAME = '#')
      OR
      (ARCHIVE_UNIT_TYPE = 'SUBPARTITION' AND SOURCE_SUBPARTITION_NAME <> '#')
    ),
  CONSTRAINT TBL_REPLICA_PARTITIONS_CK3 CHECK
    (
      (ARCHIVE_UNIT_TYPE = 'PARTITION' AND SUBPARTITION_NAME = '#')
      OR
      (ARCHIVE_UNIT_TYPE = 'SUBPARTITION' AND SUBPARTITION_NAME <> '#')
    ),
  CONSTRAINT TBL_REPLICA_PARTITIONS_CK4 CHECK
    (
      (ARCHIVE_UNIT_TYPE = 'PARTITION' AND SUBPARTITION_HIGH_VALUE = '#')
      OR
      (ARCHIVE_UNIT_TYPE = 'SUBPARTITION' AND SUBPARTITION_HIGH_VALUE <> '#')
    ),
  CONSTRAINT TBL_REPLICA_PARTITIONS_CK5 CHECK (REPLICA_STATUS IN ('Y', 'N')),
  CONSTRAINT TBL_REPLICA_PARTITIONS_CK6 CHECK (QUALITY_STATUS IN ('Y', 'N')),
  CONSTRAINT TBL_REPLICA_PARTITIONS_CK7 CHECK (PURGE_STATUS IN ('Y', 'N'))
);

CREATE INDEX TBL_REPLICA_PARTITIONS_IX1
  ON TBL_REPLICA_PARTITIONS
  (
    SOURCE_DB_LINK,
    SOURCE_OWNER,
    SOURCE_TABLE_NAME,
    REPLICA_STATUS,
    QUALITY_STATUS,
    PURGE_STATUS
  );
