CREATE TABLE TBL_REPLICA_TABLES
(
  SOURCE_DB_LINK    VARCHAR2(128) NOT NULL,
  SOURCE_OWNER      VARCHAR2(128) NOT NULL,
  SOURCE_TABLE_NAME VARCHAR2(128) NOT NULL,
  TARGET_OWNER      VARCHAR2(128) NOT NULL,
  TARGET_TABLE_NAME VARCHAR2(128) NOT NULL,
  PARALLEL_DEGREE   NUMBER        DEFAULT 4 NOT NULL,
  TABLESPACE_NAME   VARCHAR2(128) DEFAULT 'USERS' NOT NULL,
  PARTITION_METHOD    VARCHAR2(20) NOT NULL,
  SUBPARTITION_METHOD VARCHAR2(20),
  REPLICATE_EXPRESSION VARCHAR2(4000) NOT NULL,
  ENABLED_FLAG      VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP,
  CONSTRAINT TBL_REPLICA_TABLES_PK PRIMARY KEY
    (SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME),
  CONSTRAINT TBL_REPLICA_TABLES_UK1 UNIQUE
    (TARGET_OWNER, TARGET_TABLE_NAME),
  CONSTRAINT TBL_REPLICA_TABLES_CK1 CHECK (ENABLED_FLAG IN ('Y', 'N')),
  CONSTRAINT TBL_REPLICA_TABLES_CK2 CHECK (PARTITION_METHOD IN ('RANGE', 'LIST')),
  CONSTRAINT TBL_REPLICA_TABLES_CK3 CHECK
    (UPPER(TRIM(SOURCE_DB_LINK)) NOT IN ('LOCAL', 'NONE')),
  CONSTRAINT TBL_REPLICA_TABLES_CK4 CHECK
    (SUBPARTITION_METHOD IS NULL OR SUBPARTITION_METHOD = 'LIST')
);
