INSERT INTO TBL_ARCHIVER_TABLES
(
  SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME,
  TARGET_OWNER, TARGET_TABLE_NAME, PARALLEL_DEGREE,
  TABLESPACE_NAME, LAST_BUSINESS_DATE, DAYS_ONLINE, PRESERVE_RULE, ENABLED_FLAG
)
VALUES
(
  UPPER('&&ACTIVE_AGENT_LINK'), UPPER('&1'), UPPER('&2'),
  UPPER('&&ACTIVE_ARCHIVER_SCHEMA'), UPPER('&3'), 4,
  UPPER('&&DEFAULT_TABLESPACE'),
  'DAT.fn_eod',
  30,
  CASE UPPER('&2')
    WHEN 'ORDERS_ARCH_SRC' THEN 'SELECT DAT.fn_eoy FROM dual'
    WHEN 'ORDERS_SUBPART_SRC' THEN 'SELECT DAT.fn_boy FROM dual UNION ALL SELECT DAT.fn_eoy FROM dual'
    ELSE NULL
  END,
  'Y'
);

INSERT INTO TBL_ARCHIVER_PARTITIONS
(
  SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME, TARGET_OWNER, TARGET_TABLE_NAME,
  ARCHIVE_UNIT_TYPE, SOURCE_PARTITION_NAME, SOURCE_SUBPARTITION_NAME,
  PARTITION_NAME, SUBPARTITION_NAME, PARTITION_HIGH_VALUE, SUBPARTITION_HIGH_VALUE,
  ARCHIVE_STATUS, QUALITY_STATUS, TRUNCATE_STATUS, SOURCE_ROW_COUNT, TARGET_ROW_COUNT
)
SELECT SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME, TARGET_OWNER, TARGET_TABLE_NAME,
       ARCHIVE_UNIT_TYPE, SOURCE_PARTITION_NAME, SOURCE_SUBPARTITION_NAME,
       PARTITION_NAME, SUBPARTITION_NAME, PARTITION_HIGH_VALUE, SUBPARTITION_HIGH_VALUE,
       'Y', 'Y', 'Y', 0, 0
  FROM VW_ARCHIVER_SOURCE_PARTITIONS
 WHERE SOURCE_DB_LINK = UPPER('&&ACTIVE_AGENT_LINK')
   AND SOURCE_OWNER = UPPER('&1')
   AND SOURCE_TABLE_NAME = UPPER('&2')
   AND SOURCE_PARTITION_NAME = 'P_ERROR';

COMMIT;
