SET DEFINE ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT Rebuilding ARCHIVER seed objects and metadata

CONNECT &&ACTIVE_ARCHIVER_SCHEMA/"&&ACTIVE_ARCHIVER_PASSWORD"@&&ACTIVE_ARCHIVER_CONNECT

DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM USER_TABLES
   WHERE TABLE_NAME IN ('TBL_ARCHIVER_TABLES', 'TBL_ARCHIVER_PARTITIONS', 'TBL_ARCHIVER_RUNS');

  IF l_count <> 3 THEN
    RAISE_APPLICATION_ERROR(-20410, 'ARCHIVER code is not installed in the configured schema');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM USER_DB_LINKS
   WHERE DB_LINK = UPPER('&&ACTIVE_AGENT_LINK');

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20411, 'ARCHIVER AGENT DB link does not exist: &&ACTIVE_AGENT_LINK');
  END IF;
END;
/

SELECT COUNT(*) FROM &&CLIENT1_SCHEMA..ORDERS_ARCH_SRC@&&ACTIVE_AGENT_LINK WHERE 1 = 0;
SELECT COUNT(*) FROM &&CLIENT1_SCHEMA..ORDERS_SUBPART_SRC@&&ACTIVE_AGENT_LINK WHERE 1 = 0;
SELECT COUNT(*) FROM &&CLIENT1_SCHEMA..ORDERS_DAILY_INT_SRC@&&ACTIVE_AGENT_LINK WHERE 1 = 0;
SELECT COUNT(*) FROM &&CLIENT2_SCHEMA..ORDERS_ARCH_SRC@&&ACTIVE_AGENT_LINK WHERE 1 = 0;
SELECT COUNT(*) FROM &&CLIENT2_SCHEMA..ORDERS_SUBPART_SRC@&&ACTIVE_AGENT_LINK WHERE 1 = 0;
SELECT COUNT(*) FROM &&CLIENT2_SCHEMA..ORDERS_DAILY_INT_SRC@&&ACTIVE_AGENT_LINK WHERE 1 = 0;

DELETE FROM TBL_ARCHIVER_PARTITIONS
 WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
   AND SOURCE_TABLE_NAME IN ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC');

DELETE FROM TBL_ARCHIVER_RUNS
 WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
   AND SOURCE_TABLE_NAME IN ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC');

DELETE FROM TBL_ARCHIVER_TABLES
 WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'))
   AND SOURCE_TABLE_NAME IN ('ORDERS_ARCH_SRC', 'ORDERS_SUBPART_SRC', 'ORDERS_DAILY_INT_SRC');

COMMIT;

@@seed_archiver_dat.sql

@@seed_archiver_target.sql TBL_ARCHIVER_CLIENT1_ORDERS
@@seed_archiver_target.sql TBL_ARCHIVER_CLIENT2_ORDERS
@@seed_archiver_list_target.sql TBL_ARCHIVER_CLIENT1_SUBPART
@@seed_archiver_list_target.sql TBL_ARCHIVER_CLIENT2_SUBPART
@@seed_archiver_list_target.sql TBL_ARCHIVER_CLIENT1_DAILY_INT
@@seed_archiver_list_target.sql TBL_ARCHIVER_CLIENT2_DAILY_INT

@@seed_archiver_metadata.sql &&CLIENT1_SCHEMA ORDERS_ARCH_SRC TBL_ARCHIVER_CLIENT1_ORDERS
@@seed_archiver_metadata.sql &&CLIENT1_SCHEMA ORDERS_SUBPART_SRC TBL_ARCHIVER_CLIENT1_SUBPART
@@seed_archiver_metadata.sql &&CLIENT1_SCHEMA ORDERS_DAILY_INT_SRC TBL_ARCHIVER_CLIENT1_DAILY_INT
@@seed_archiver_metadata.sql &&CLIENT2_SCHEMA ORDERS_ARCH_SRC TBL_ARCHIVER_CLIENT2_ORDERS
@@seed_archiver_metadata.sql &&CLIENT2_SCHEMA ORDERS_SUBPART_SRC TBL_ARCHIVER_CLIENT2_SUBPART
@@seed_archiver_metadata.sql &&CLIENT2_SCHEMA ORDERS_DAILY_INT_SRC TBL_ARCHIVER_CLIENT2_DAILY_INT

PROMPT ARCHIVER seed rebuild completed
