BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TBL_ARCHIVER_CLIENT1_LIST_VARCHAR PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE TBL_ARCHIVER_CLIENT1_LIST_VARCHAR
(
  ORDER_ID    NUMBER NOT NULL,
  REGION_CODE VARCHAR2(10) NOT NULL,
  STATUS_CODE VARCHAR2(20) NOT NULL,
  AMOUNT      NUMBER(12,2) NOT NULL,
  CREATED_AT  TIMESTAMP NOT NULL
)
PARTITION BY LIST (REGION_CODE)
SUBPARTITION BY LIST (STATUS_CODE)
SUBPARTITION TEMPLATE
(
  SUBPARTITION SP_OPEN VALUES ('NEW', 'PAID'),
  SUBPARTITION SP_DONE VALUES ('SHIPPED', 'CLOSED')
)
(
  PARTITION P_ERROR VALUES ('#ERROR#')
);
