BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ' || DBMS_ASSERT.SIMPLE_SQL_NAME(UPPER('&1')) || ' PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE &1
(
  ORDER_ID     NUMBER NOT NULL,
  CUSTOMER_ID  NUMBER NOT NULL,
  ORDER_DATE   DATE NOT NULL,
  STATUS_CODE  VARCHAR2(20) NOT NULL,
  AMOUNT       NUMBER(12,2) NOT NULL,
  CREATED_AT   TIMESTAMP NOT NULL
)
PARTITION BY RANGE (ORDER_DATE)
(
  PARTITION P_ERROR VALUES LESS THAN
    (TO_DATE(' 1800-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
);

CREATE INDEX &1._LIX1 ON &1 (CUSTOMER_ID, ORDER_DATE) LOCAL;
CREATE INDEX &1._LIX2 ON &1 (STATUS_CODE, ORDER_DATE) LOCAL;

