SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Creating CLIENT1_LOOPBACK_LINK from CARCH to CAGENT1

BEGIN
  EXECUTE IMMEDIATE 'DROP DATABASE LINK CLIENT1_LOOPBACK_LINK';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2024 THEN
      RAISE;
    END IF;
END;
/

CREATE DATABASE LINK CLIENT1_LOOPBACK_LINK
  CONNECT TO CAGENT1 IDENTIFIED BY "Cagent1Dev2026_42"
  USING '//localhost:1521/FREEPDB1';

SELECT * FROM dual@CLIENT1_LOOPBACK_LINK;

PROMPT CLIENT1_LOOPBACK_LINK created

