SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@deploy/config/install_config.local.sql

PROMPT Connecting to configured ARCHIVER database
CONNECT &&APPLICATION_SCHEMA/"&&APPLICATION_PASSWORD"@&&ARCHIVER_CONNECT

SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@deploy/layer2/install_layer2_core.sql

PROMPT Standalone ARCHIVER component installation completed
