SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TBL_ARCHIVER_ORDERS_SRC PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE TBL_ARCHIVER_ORDERS_SRC
(
  ORDER_ID     NUMBER NOT NULL,
  CUSTOMER_ID  NUMBER NOT NULL,
  ORDER_DATE   DATE NOT NULL,
  STATUS_CODE  VARCHAR2(20) NOT NULL,
  AMOUNT       NUMBER(12,2) NOT NULL,
  CREATED_AT   TIMESTAMP NOT NULL
)
PARTITION BY RANGE (ORDER_DATE)
(
  PARTITION P_ERROR VALUES LESS THAN
    (TO_DATE(' 1800-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
);

CREATE INDEX TBL_ARCHIVER_ORDERS_SRC_LIX1
  ON TBL_ARCHIVER_ORDERS_SRC (CUSTOMER_ID, ORDER_DATE)
  LOCAL;

CREATE INDEX TBL_ARCHIVER_ORDERS_SRC_LIX2
  ON TBL_ARCHIVER_ORDERS_SRC (STATUS_CODE, ORDER_DATE)
  LOCAL;
