SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Installing CARCH.ORDERS_DAILY_INT_SRC_2 target table

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_DAILY_INT_SRC_2 PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE ORDERS_DAILY_INT_SRC_2
(
  ORDER_ID     NUMBER NOT NULL,
  CUSTOMER_ID  NUMBER NOT NULL,
  ORDER_DATE   DATE NOT NULL,
  STATUS_CODE  VARCHAR2(20) NOT NULL,
  REGION_CODE  VARCHAR2(10) NOT NULL,
  AMOUNT       NUMBER(12,2) NOT NULL,
  CREATED_AT   TIMESTAMP NOT NULL
)
PARTITION BY RANGE (ORDER_DATE)
SUBPARTITION BY LIST (STATUS_CODE)
SUBPARTITION TEMPLATE
(
  SUBPARTITION SP_OPEN VALUES ('NEW', 'PAID'),
  SUBPARTITION SP_DONE VALUES ('SHIPPED', 'CLOSED')
)
(
  PARTITION P_ERROR VALUES LESS THAN
    (TO_DATE(' 1800-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
);

CREATE INDEX ORDERS_DAILY_INT_SRC_2_LIX1
  ON ORDERS_DAILY_INT_SRC_2 (CUSTOMER_ID, ORDER_DATE)
  LOCAL;

CREATE INDEX ORDERS_DAILY_INT_SRC_2_LIX2
  ON ORDERS_DAILY_INT_SRC_2 (REGION_CODE, ORDER_DATE)
  LOCAL;

PROMPT CARCH.ORDERS_DAILY_INT_SRC_2 target table install completed
