SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Migrating TW_ARCHIVE_PARTITIONS source partition name columns

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM user_tab_columns
   WHERE table_name = 'TW_ARCHIVE_PARTITIONS'
     AND column_name = 'SOURCE_PARTITION_NAME';

  IF l_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TW_ARCHIVE_PARTITIONS ADD SOURCE_PARTITION_NAME VARCHAR2(128)';
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM user_tab_columns
   WHERE table_name = 'TW_ARCHIVE_PARTITIONS'
     AND column_name = 'SOURCE_SUBPARTITION_NAME';

  IF l_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE TW_ARCHIVE_PARTITIONS ADD SOURCE_SUBPARTITION_NAME VARCHAR2(128) DEFAULT '#'
    ]';
  END IF;
END;
/

UPDATE TW_ARCHIVE_PARTITIONS
   SET SOURCE_PARTITION_NAME = COALESCE(SOURCE_PARTITION_NAME, PARTITION_NAME),
       SOURCE_SUBPARTITION_NAME = CASE
                                    WHEN ARCHIVE_UNIT_TYPE = 'SUBPARTITION'
                                      THEN COALESCE(NULLIF(SOURCE_SUBPARTITION_NAME, '#'), SUBPARTITION_NAME)
                                    ELSE '#'
                                  END
 WHERE SOURCE_PARTITION_NAME IS NULL
    OR SOURCE_SUBPARTITION_NAME IS NULL
    OR (ARCHIVE_UNIT_TYPE = 'SUBPARTITION' AND SOURCE_SUBPARTITION_NAME = '#')
    OR (ARCHIVE_UNIT_TYPE = 'PARTITION' AND SOURCE_SUBPARTITION_NAME <> '#');

COMMIT;

DECLARE
  l_nullable VARCHAR2(1);
BEGIN
  SELECT nullable
    INTO l_nullable
    FROM user_tab_columns
   WHERE table_name = 'TW_ARCHIVE_PARTITIONS'
     AND column_name = 'SOURCE_PARTITION_NAME';

  IF l_nullable = 'Y' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TW_ARCHIVE_PARTITIONS MODIFY SOURCE_PARTITION_NAME NOT NULL';
  END IF;

  SELECT nullable
    INTO l_nullable
    FROM user_tab_columns
   WHERE table_name = 'TW_ARCHIVE_PARTITIONS'
     AND column_name = 'SOURCE_SUBPARTITION_NAME';

  IF l_nullable = 'Y' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TW_ARCHIVE_PARTITIONS MODIFY SOURCE_SUBPARTITION_NAME NOT NULL';
  END IF;
END;
/

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM user_constraints
   WHERE table_name = 'TW_ARCHIVE_PARTITIONS'
     AND constraint_name = 'TW_ARCHIVE_PARTITIONS_CK6';

  IF l_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE TW_ARCHIVE_PARTITIONS ADD CONSTRAINT TW_ARCHIVE_PARTITIONS_CK6 CHECK
      (
        (ARCHIVE_UNIT_TYPE = 'PARTITION' AND SOURCE_SUBPARTITION_NAME = '#')
        OR
        (ARCHIVE_UNIT_TYPE = 'SUBPARTITION' AND SOURCE_SUBPARTITION_NAME <> '#')
      )
    ]';
  END IF;
END;
/

PROMPT TW_ARCHIVE_PARTITIONS source partition name migration completed
