SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Resetting CLIENT1_LOOPBACK_LINK archive metadata

DELETE FROM TW_ARCHIVE_PARTITIONS
 WHERE SOURCE_DB_LINK = 'CLIENT1_LOOPBACK_LINK'
   AND SOURCE_OWNER = 'CLIENT1'
   AND SOURCE_TABLE_NAME = 'ORDERS_ARCH_SRC';

COMMIT;

PROMPT CLIENT1_LOOPBACK_LINK archive metadata reset completed

