SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Running CLIENT1_LOOPBACK_LINK remote-path smoke test

SELECT CAGENT1.PKG_ARCHIVE_AGENT.health_check@CLIENT1_LOOPBACK_LINK AS AGENT_HEALTH
  FROM dual;

SELECT CAGENT1.PKG_ARCHIVE_AGENT.get_row_count@CLIENT1_LOOPBACK_LINK
       ('CLIENT1', 'ORDERS_ARCH_SRC', 'P202401', NULL) AS P202401_ROWS
  FROM dual;

SELECT COUNT(*) AS REMOTE_SOURCE_ROWS
  FROM CLIENT1.ORDERS_ARCH_SRC@CLIENT1_LOOPBACK_LINK;

BEGIN
  PKG_ARCHIVE_DISCOVERY.discover_table
  (
    p_source_db_link => 'CLIENT1_LOOPBACK_LINK',
    p_owner       => 'CLIENT1',
    p_table_name  => 'ORDERS_ARCH_SRC',
    p_execute     => 'N'
  );
END;
/

PROMPT CLIENT1_LOOPBACK_LINK remote-path smoke test completed

