SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Running CLIENT1_LOOPBACK_LINK truncate preview smoke test

BEGIN
  PKG_ARCHIVE_TRUNCATE.prc_truncate
  (
    p_execute           => 'N',
    p_target_owner      => 'CARCH',
    p_target_table_name => 'ORDERS_ARCH_SRC'
  );
END;
/

SELECT CAGENT1.PKG_ARCHIVE_AGENT.fn_get_row_count@CLIENT1_LOOPBACK_LINK
       ('CLIENT1', 'ORDERS_ARCH_SRC', 'P202401', NULL) AS P202401_ROWS_AFTER_PREVIEW
  FROM dual;

SELECT p.SOURCE_DB_LINK,
       p.PARTITION_NAME,
       p.QUALITY_STATUS,
       p.TRUNCATE_STATUS
  FROM TW_ARCHIVE_PARTITIONS p
 WHERE p.SOURCE_DB_LINK = 'CLIENT1_LOOPBACK_LINK'
 ORDER BY p.PARTITION_POSITION, p.SUBPARTITION_POSITION;

PROMPT CLIENT1_LOOPBACK_LINK truncate preview smoke test completed
