SET DEFINE ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT Seeding AGENT client tables

CONNECT &&ACTIVE_AGENT_SCHEMA/"&&ACTIVE_AGENT_PASSWORD"@&&ACTIVE_AGENT_CONNECT

/* Clear existing data */
DELETE FROM tbl_agent_client_tables
 WHERE SOURCE_OWNER IN (UPPER('&&CLIENT1_SCHEMA'), UPPER('&&CLIENT2_SCHEMA'));

/* Insert CLIENT1 tables */
INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT1_SCHEMA'), 'ORDERS_ARCH_SRC');

INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT1_SCHEMA'), 'ORDERS_SUBPART_SRC');

INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT1_SCHEMA'), 'ORDERS_DAILY_INT_SRC');

INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT1_SCHEMA'), 'ORDERS_LIST_DATE_SRC');

INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT1_SCHEMA'), 'ORDERS_LIST_NUMBER_SRC');

INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT1_SCHEMA'), 'ORDERS_LIST_VARCHAR_SRC');

/* Insert CLIENT2 tables */
INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT2_SCHEMA'), 'ORDERS_ARCH_SRC');

INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT2_SCHEMA'), 'ORDERS_SUBPART_SRC');

INSERT INTO tbl_agent_client_tables (SOURCE_OWNER, SOURCE_TABLE_NAME)
VALUES (UPPER('&&CLIENT2_SCHEMA'), 'ORDERS_DAILY_INT_SRC');

COMMIT;

PROMPT AGENT seed rebuild completed
