INSERT INTO TBL_REPLICA_TABLES
(
  SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME,
  TARGET_OWNER, TARGET_TABLE_NAME, PARALLEL_DEGREE,
  TABLESPACE_NAME, PARTITION_METHOD, SUBPARTITION_METHOD,
  REPLICATE_EXPRESSION, ENABLED_FLAG
)
VALUES
(
  UPPER('&&ACTIVE_ARCHIVER_LINK'), UPPER('&&ACTIVE_ARCHIVER_SCHEMA'), UPPER('&1'),
  UPPER('&&ACTIVE_REPLICA_SCHEMA'), UPPER('&2'), 4,
  UPPER('&&DEFAULT_TABLESPACE'),
  CASE UPPER('&1')
    WHEN 'TBL_ARCHIVER_CLIENT1_LIST_DATE' THEN 'LIST'
    WHEN 'TBL_ARCHIVER_CLIENT1_LIST_NUMBER' THEN 'LIST'
    WHEN 'TBL_ARCHIVER_CLIENT1_LIST_VARCHAR' THEN 'LIST'
    ELSE 'RANGE'
  END,
  CASE
    WHEN UPPER('&1') LIKE '%SUBPART' OR UPPER('&1') LIKE '%DAILY_INT'
      OR UPPER('&1') = 'TBL_ARCHIVER_CLIENT1_LIST_VARCHAR' THEN 'LIST'
  END,
  CASE UPPER('&1')
    WHEN 'TBL_ARCHIVER_CLIENT1_LIST_DATE' THEN
      '<partition_high_value> >= DATE ''2024-01-01'''
    WHEN 'TBL_ARCHIVER_CLIENT1_LIST_NUMBER' THEN
      '10 IN (<partition_high_value>) OR 20 IN (<partition_high_value>)'
    WHEN 'TBL_ARCHIVER_CLIENT1_LIST_VARCHAR' THEN
      '''N'' IN (<partition_high_value>) OR ''W'' IN (<partition_high_value>)'
    ELSE '1=1'
  END,
  'Y'
);

INSERT INTO TBL_REPLICA_PARTITIONS
(
  SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME, TARGET_OWNER, TARGET_TABLE_NAME,
  ARCHIVE_UNIT_TYPE, SOURCE_PARTITION_NAME, SOURCE_SUBPARTITION_NAME,
  PARTITION_NAME, SUBPARTITION_NAME, PARTITION_HIGH_VALUE, SUBPARTITION_HIGH_VALUE,
  REPLICA_STATUS, QUALITY_STATUS, PURGE_STATUS, SOURCE_ROW_COUNT, TARGET_ROW_COUNT
)
SELECT UPPER('&&ACTIVE_ARCHIVER_LINK'), UPPER('&&ACTIVE_ARCHIVER_SCHEMA'), UPPER('&1'),
       UPPER('&&ACTIVE_REPLICA_SCHEMA'), UPPER('&2'),
       ARCHIVE_UNIT_TYPE, PARTITION_NAME, SUBPARTITION_NAME,
       PARTITION_NAME, SUBPARTITION_NAME, PARTITION_HIGH_VALUE, SUBPARTITION_HIGH_VALUE,
       'Y', 'Y', 'Y', 0, 0
  FROM VW_REPLICA_SOURCE_PARTITIONS
 WHERE SOURCE_DB_LINK = UPPER('&&ACTIVE_ARCHIVER_LINK')
   AND SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
   AND SOURCE_TABLE_NAME = UPPER('&1')
   AND
   (
     PARTITION_NAME = 'P_ERROR'
     OR UPPER(TRIM(PARTITION_HIGH_VALUE)) IN ('MAXVALUE', 'DEFAULT', 'NULL')
     OR UPPER(TRIM(SUBPARTITION_HIGH_VALUE)) IN ('DEFAULT', 'NULL')
   );

COMMIT;
