BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TBL_REPLICA_CLIENT1_LIST_DATE PURGE';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE TBL_REPLICA_CLIENT1_LIST_DATE
(
  ORDER_ID NUMBER NOT NULL, ORDER_DATE DATE NOT NULL,
  STATUS_CODE VARCHAR2(20) NOT NULL, AMOUNT NUMBER(12,2) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL
)
PARTITION BY LIST (ORDER_DATE)
(
  PARTITION P_ERROR VALUES (DATE '1800-01-01')
);
