BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TBL_REPLICA_CLIENT1_LIST_NUMBER PURGE';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE TBL_REPLICA_CLIENT1_LIST_NUMBER
(
  ORDER_ID NUMBER NOT NULL, BUCKET_ID NUMBER NOT NULL,
  STATUS_CODE VARCHAR2(20) NOT NULL, AMOUNT NUMBER(12,2) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL
)
PARTITION BY LIST (BUCKET_ID)
(
  PARTITION P_ERROR VALUES (-999999999)
);
