INSERT INTO TBL_REPLICA_TABLES
(
  SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME,
  TARGET_OWNER, TARGET_TABLE_NAME, PARALLEL_DEGREE,
  TABLESPACE_NAME, DAYS_ONLINE, ENABLED_FLAG
)
VALUES
(
  UPPER('&&ACTIVE_ARCHIVER_LINK'), UPPER('&&ACTIVE_ARCHIVER_SCHEMA'), UPPER('&1'),
  UPPER('&&ACTIVE_REPLICA_SCHEMA'), UPPER('&2'), 4,
  UPPER('&&DEFAULT_TABLESPACE'), 365, 'Y'
);

INSERT INTO TBL_REPLICA_PARTITIONS
(
  SOURCE_DB_LINK, SOURCE_OWNER, SOURCE_TABLE_NAME, TARGET_OWNER, TARGET_TABLE_NAME,
  ARCHIVE_UNIT_TYPE, SOURCE_PARTITION_NAME, SOURCE_SUBPARTITION_NAME,
  PARTITION_NAME, SUBPARTITION_NAME, PARTITION_HIGH_VALUE, SUBPARTITION_HIGH_VALUE,
  REPLICA_STATUS, QUALITY_STATUS, PURGE_STATUS, SOURCE_ROW_COUNT, TARGET_ROW_COUNT
)
SELECT UPPER('&&ACTIVE_ARCHIVER_LINK'), UPPER('&&ACTIVE_ARCHIVER_SCHEMA'), UPPER('&1'),
       UPPER('&&ACTIVE_REPLICA_SCHEMA'), UPPER('&2'),
       ARCHIVE_UNIT_TYPE, PARTITION_NAME, SUBPARTITION_NAME,
       PARTITION_NAME, SUBPARTITION_NAME, PARTITION_HIGH_VALUE, SUBPARTITION_HIGH_VALUE,
       'Y', 'Y', 'Y', 0, 0
  FROM REPLICA_ARCHIVER_PARTITIONS_SRC
 WHERE TARGET_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
   AND TARGET_TABLE_NAME = UPPER('&1')
   AND PARTITION_NAME = 'P_ERROR';

COMMIT;
