SET DEFINE ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT Rebuilding REPLICA seed objects and metadata

CONNECT &&ACTIVE_REPLICA_SCHEMA/"&&ACTIVE_REPLICA_PASSWORD"@&&ACTIVE_REPLICA_CONNECT

DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM USER_TABLES
   WHERE TABLE_NAME IN ('TBL_REPLICA_TABLES', 'TBL_REPLICA_PARTITIONS', 'TBL_REPLICA_RUNS');

  IF l_count <> 3 THEN
    RAISE_APPLICATION_ERROR(-20420, 'REPLICA code is not installed in the configured schema');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM USER_DB_LINKS
   WHERE DB_LINK = UPPER('&&ACTIVE_ARCHIVER_LINK');

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20421, 'REPLICA ARCHIVER DB link does not exist: &&ACTIVE_ARCHIVER_LINK');
  END IF;
END;
/

SELECT COUNT(*) FROM &&ACTIVE_ARCHIVER_SCHEMA..TBL_ARCHIVER_PARTITIONS@&&ACTIVE_ARCHIVER_LINK WHERE 1 = 0;

DELETE FROM TBL_REPLICA_PARTITIONS
 WHERE SOURCE_TABLE_NAME IN
       ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
        'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT');

DELETE FROM TBL_REPLICA_RUNS
 WHERE SOURCE_TABLE_NAME IN
       ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
        'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT');

DELETE FROM TBL_REPLICA_TABLES
 WHERE SOURCE_TABLE_NAME IN
       ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
        'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT');

COMMIT;

@@seed_replica_target.sql TBL_REPLICA_CLIENT1_ORDERS
@@seed_replica_target.sql TBL_REPLICA_CLIENT2_ORDERS
@@seed_replica_list_target.sql TBL_REPLICA_CLIENT1_SUBPART
@@seed_replica_list_target.sql TBL_REPLICA_CLIENT2_SUBPART
@@seed_replica_list_target.sql TBL_REPLICA_CLIENT1_DAILY_INT
@@seed_replica_list_target.sql TBL_REPLICA_CLIENT2_DAILY_INT

@@seed_replica_metadata.sql TBL_ARCHIVER_CLIENT1_ORDERS TBL_REPLICA_CLIENT1_ORDERS
@@seed_replica_metadata.sql TBL_ARCHIVER_CLIENT1_SUBPART TBL_REPLICA_CLIENT1_SUBPART
@@seed_replica_metadata.sql TBL_ARCHIVER_CLIENT1_DAILY_INT TBL_REPLICA_CLIENT1_DAILY_INT
@@seed_replica_metadata.sql TBL_ARCHIVER_CLIENT2_ORDERS TBL_REPLICA_CLIENT2_ORDERS
@@seed_replica_metadata.sql TBL_ARCHIVER_CLIENT2_SUBPART TBL_REPLICA_CLIENT2_SUBPART
@@seed_replica_metadata.sql TBL_ARCHIVER_CLIENT2_DAILY_INT TBL_REPLICA_CLIENT2_DAILY_INT

PROMPT REPLICA seed rebuild completed
