SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT Installing distributed AGENT &1
CONNECT &3/"&4"@&2

SET DEFINE OFF
@deploy/layer1/install_layer1_agent.sql

SET DEFINE ON
