SET DEFINE ON
@deploy/config/distributed_topology.local.sql

CONNECT &&DISTRIBUTED_REPLICA_SCHEMA/"&&DISTRIBUTED_REPLICA_PASSWORD"@&&DISTRIBUTED_REPLICA_CONNECT
@deploy/distributed/create_remote_link.sql &&DISTRIBUTED_REPLICA_ARCHIVER_LINK &&DISTRIBUTED_ARCHIVER_CONNECT &&DISTRIBUTED_ARCHIVER_SCHEMA &&DISTRIBUTED_ARCHIVER_PASSWORD
CREATE OR REPLACE SYNONYM REPLICA_ARCHIVER_PARTITIONS_SRC
  FOR &&DISTRIBUTED_ARCHIVER_SCHEMA..TBL_ARCHIVER_PARTITIONS@&&DISTRIBUTED_REPLICA_ARCHIVER_LINK;

SET DEFINE OFF
@deploy/layer3/install_layer3_replica.sql
