SET DEFINE ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

@deploy/config/distributed_topology.local.sql

CONNECT &&DISTRIBUTED_ARCHIVER_ADMIN_USER/"&&DISTRIBUTED_ARCHIVER_ADMIN_PASSWORD"@&&DISTRIBUTED_ARCHIVER_CONNECT AS &&DISTRIBUTED_ARCHIVER_ADMIN_ROLE
GRANT SELECT ON CLIENT1.ORDERS_ARCH_SRC TO PMGR_D_AGENT1;
GRANT SELECT ON CLIENT1.ORDERS_ARCH_SRC TO PMGR_D_AGENT2;

CONNECT &&DISTRIBUTED_ARCHIVER_SCHEMA/"&&DISTRIBUTED_ARCHIVER_PASSWORD"@&&DISTRIBUTED_ARCHIVER_CONNECT
SET DEFINE OFF
@deploy/layer2/install_archiver_orders_target.sql
@deploy/distributed/install_archiver_orders_target2.sql
@deploy/distributed/seed_archiver_sources.sql

SET DEFINE ON
CONNECT &&DISTRIBUTED_REPLICA_SCHEMA/"&&DISTRIBUTED_REPLICA_PASSWORD"@&&DISTRIBUTED_REPLICA_CONNECT
SET DEFINE OFF
@deploy/layer3/install_replica_orders_target.sql
@deploy/distributed/seed_replica_source.sql
