SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CONNECT &1/"&2"@&4 AS &3
DEFINE APPLICATION_SCHEMA = &5
DEFINE APPLICATION_PASSWORD = &6
DEFINE DEFAULT_TABLESPACE = USERS
DEFINE TEMPORARY_TABLESPACE = TEMP
@deploy/provision/create_application_schema.sql
