SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

@deploy/config/distributed_topology.local.sql

DEFINE DISTRIBUTED_AGENT_ACTION = deploy/distributed/drop_agent_instance.sql
@&&DISTRIBUTED_AGENT_MANIFEST

@deploy/distributed/drop_schema.sql &&DISTRIBUTED_ARCHIVER_ADMIN_USER &&DISTRIBUTED_ARCHIVER_ADMIN_PASSWORD &&DISTRIBUTED_ARCHIVER_ADMIN_ROLE &&DISTRIBUTED_ARCHIVER_CONNECT &&DISTRIBUTED_ARCHIVER_SCHEMA
@deploy/distributed/drop_schema.sql &&DISTRIBUTED_REPLICA_ADMIN_USER &&DISTRIBUTED_REPLICA_ADMIN_PASSWORD &&DISTRIBUTED_REPLICA_ADMIN_ROLE &&DISTRIBUTED_REPLICA_CONNECT &&DISTRIBUTED_REPLICA_SCHEMA

PROMPT Local distributed simulation schemas dropped
