BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_LIST_VARCHAR_SRC PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE ORDERS_LIST_VARCHAR_SRC
(
  ORDER_ID    NUMBER NOT NULL,
  REGION_CODE VARCHAR2(10) NOT NULL,
  STATUS_CODE VARCHAR2(20) NOT NULL,
  AMOUNT      NUMBER(12,2) NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
PARTITION BY LIST (REGION_CODE)
SUBPARTITION BY LIST (STATUS_CODE)
SUBPARTITION TEMPLATE
(
  SUBPARTITION SP_OPEN VALUES ('NEW', 'PAID'),
  SUBPARTITION SP_DONE VALUES ('SHIPPED', 'CLOSED')
)
(
  PARTITION P_ERROR VALUES ('#ERROR#'),
  PARTITION P_REGION_NS VALUES ('N', 'S'),
  PARTITION P_REGION_WE VALUES ('W', 'E')
);

INSERT INTO ORDERS_LIST_VARCHAR_SRC (ORDER_ID, REGION_CODE, STATUS_CODE, AMOUNT)
SELECT LEVEL,
       CASE MOD(LEVEL, 4) WHEN 0 THEN 'N' WHEN 1 THEN 'S' WHEN 2 THEN 'W' ELSE 'E' END,
       CASE MOD(LEVEL, 4) WHEN 0 THEN 'NEW' WHEN 1 THEN 'PAID' WHEN 2 THEN 'SHIPPED' ELSE 'CLOSED' END,
       LEVEL * 3.75
  FROM dual
CONNECT BY LEVEL <= 80;

COMMIT;
