BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_LIST_NUMBER_SRC PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE ORDERS_LIST_NUMBER_SRC
(
  ORDER_ID    NUMBER NOT NULL,
  BUCKET_ID   NUMBER NOT NULL,
  STATUS_CODE VARCHAR2(20) NOT NULL,
  AMOUNT      NUMBER(12,2) NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
PARTITION BY LIST (BUCKET_ID)
(
  PARTITION P_ERROR VALUES (-999999999),
  PARTITION P_BUCKET_LOW VALUES (10, 11),
  PARTITION P_BUCKET_HIGH VALUES (20, 21)
);

INSERT INTO ORDERS_LIST_NUMBER_SRC (ORDER_ID, BUCKET_ID, STATUS_CODE, AMOUNT)
SELECT LEVEL,
       CASE MOD(LEVEL, 4) WHEN 0 THEN 10 WHEN 1 THEN 11 WHEN 2 THEN 20 ELSE 21 END,
       CASE MOD(LEVEL, 2) WHEN 0 THEN 'PAID' ELSE 'CLOSED' END,
       LEVEL * 2.50
  FROM dual
CONNECT BY LEVEL <= 40;

COMMIT;
