BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS_LIST_DATE_SRC PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE ORDERS_LIST_DATE_SRC
(
  ORDER_ID    NUMBER NOT NULL,
  ORDER_DATE  DATE NOT NULL,
  STATUS_CODE VARCHAR2(20) NOT NULL,
  AMOUNT      NUMBER(12,2) NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
PARTITION BY LIST (ORDER_DATE)
(
  PARTITION P_ERROR VALUES (DATE '1800-01-01'),
  PARTITION P_DATE_1 VALUES (DATE '2024-01-15'),
  PARTITION P_DATE_2 VALUES (DATE '2024-02-15')
);

INSERT INTO ORDERS_LIST_DATE_SRC (ORDER_ID, ORDER_DATE, STATUS_CODE, AMOUNT)
SELECT LEVEL,
       CASE MOD(LEVEL, 2) WHEN 0 THEN DATE '2024-01-15' ELSE DATE '2024-02-15' END,
       CASE MOD(LEVEL, 2) WHEN 0 THEN 'PAID' ELSE 'CLOSED' END,
       LEVEL * 1.25
  FROM dual
CONNECT BY LEVEL <= 40;

COMMIT;
