CREATE OR REPLACE TRIGGER TRG_ARCHIVER_TABLES_PRESERVE_CALC
  BEFORE INSERT OR UPDATE OF PRESERVE_RULE ON TBL_ARCHIVER_TABLES
  FOR EACH ROW
DECLARE
  l_date DATE;
BEGIN
  IF :NEW.PRESERVE_RULE IS NULL THEN
    :NEW.PRESERVE_CALC := NULL;
    :NEW.UPDATED_AT := SYSDATE;
    RETURN;
  END IF;

  BEGIN
    SELECT COLUMN_VALUE INTO l_date
      FROM TABLE(FN_ARCHIVER_VALIDATE_PRESERVE(:NEW.PRESERVE_RULE))
     WHERE ROWNUM = 1;

    IF l_date IS NULL THEN
      :NEW.PRESERVE_CALC := 'ERROR: execute failed';
    ELSE
      :NEW.PRESERVE_CALC := 'CORRECT';
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      :NEW.PRESERVE_CALC := 'CORRECT';
    WHEN OTHERS THEN
      :NEW.PRESERVE_CALC := 'ERROR: ' || SQLERRM;
  END;

  :NEW.UPDATED_AT := SYSDATE;
END;
/
