SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Granting CAGENT1 archive agent access to CARCH

GRANT EXECUTE ON ARCHIVE_PARTITION_INFO_OBJ TO CARCH;
GRANT EXECUTE ON ARCHIVE_PARTITION_INFO_TAB TO CARCH;
GRANT EXECUTE ON PKG_ARCHIVE_AGENT TO CARCH;
GRANT SELECT ON ARCHIVE_PARTITION_INFO_VW TO CARCH;

PROMPT CAGENT1 archive agent grants completed
