SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT Loading configured application schema
@deploy/config/install_config.local.sql

PROMPT Connecting to configured AGENT database &1
CONNECT &&APPLICATION_SCHEMA/"&&APPLICATION_PASSWORD"@&1

SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

@deploy/layer1/install_layer1_agent.sql

PROMPT Standalone AGENT component installation completed
