PROMPT REPLICA 001 - metadata

CONNECT &&ACTIVE_REPLICA_SCHEMA/"&&ACTIVE_REPLICA_PASSWORD"@&&ACTIVE_REPLICA_CONNECT

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_TABLES
   WHERE SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
     AND SOURCE_TABLE_NAME IN
         ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
          'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT');

  IF l_count != 6 THEN
    RAISE_APPLICATION_ERROR(-20580, 'REPLICA expected 6 seeded table configs, got ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_TABLES
   WHERE SOURCE_DB_LINK IS NULL
      OR UPPER(TRIM(SOURCE_DB_LINK)) IN ('LOCAL', 'NONE');

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20581, 'REPLICA has invalid SOURCE_DB_LINK rows: ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_PARTITIONS
   WHERE SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
     AND SOURCE_TABLE_NAME IN
         ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
          'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT')
     AND SOURCE_PARTITION_NAME = 'P_ERROR';

  IF l_count != 10 THEN
    RAISE_APPLICATION_ERROR(-20582, 'REPLICA expected 10 seeded P_ERROR partition rows, got ' || l_count);
  END IF;
END;
/

PROMPT REPLICA 001 completed
