PROMPT REPLICA 001 - metadata

CONNECT &&ACTIVE_REPLICA_SCHEMA/"&&ACTIVE_REPLICA_PASSWORD"@&&ACTIVE_REPLICA_CONNECT

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_TABLES
   WHERE SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
     AND SOURCE_TABLE_NAME IN
         ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
          'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT',
          'TBL_ARCHIVER_CLIENT1_LIST_DATE', 'TBL_ARCHIVER_CLIENT1_LIST_NUMBER', 'TBL_ARCHIVER_CLIENT1_LIST_VARCHAR');

  IF l_count != 9 THEN
    RAISE_APPLICATION_ERROR(-20580, 'REPLICA expected 9 seeded table configs, got ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_TABLES
   WHERE SOURCE_DB_LINK IS NULL
      OR UPPER(TRIM(SOURCE_DB_LINK)) IN ('LOCAL', 'NONE');

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20581, 'REPLICA has invalid SOURCE_DB_LINK rows: ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_PARTITIONS
   WHERE SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
     AND SOURCE_TABLE_NAME IN
          ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
          'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT',
          'TBL_ARCHIVER_CLIENT1_LIST_DATE', 'TBL_ARCHIVER_CLIENT1_LIST_NUMBER', 'TBL_ARCHIVER_CLIENT1_LIST_VARCHAR')
     AND (SOURCE_PARTITION_NAME = 'P_ERROR' OR UPPER(TRIM(PARTITION_HIGH_VALUE)) = 'MAXVALUE')
     AND REPLICA_STATUS = 'Y' AND QUALITY_STATUS = 'Y' AND PURGE_STATUS = 'Y';

  IF l_count != 20 THEN
    RAISE_APPLICATION_ERROR(-20582, 'REPLICA expected 20 seeded technical rows, got ' || l_count);
  END IF;

  SELECT COUNT(*) INTO l_count
    FROM TBL_REPLICA_TABLES
   WHERE PARTITION_METHOD = 'LIST'
     AND REPLICATE_EXPRESSION IS NOT NULL;

  IF l_count != 3 THEN
    RAISE_APPLICATION_ERROR(-20583, 'REPLICA expected 3 LIST configurations, got ' || l_count);
  END IF;
END;
/

PROMPT REPLICA 001 completed
