PROMPT REPLICA 002 - ARCHIVER DB link

CONNECT &&ACTIVE_REPLICA_SCHEMA/"&&ACTIVE_REPLICA_PASSWORD"@&&ACTIVE_REPLICA_CONNECT

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM USER_DB_LINKS
   WHERE DB_LINK = UPPER('&&ACTIVE_ARCHIVER_LINK');

  IF l_count != 1 THEN
    RAISE_APPLICATION_ERROR(-20590, 'REPLICA ARCHIVER DB link not found: &&ACTIVE_ARCHIVER_LINK');
  END IF;

  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM dual@' || DBMS_ASSERT.SIMPLE_SQL_NAME('&&ACTIVE_ARCHIVER_LINK')
    INTO l_count;

  EXECUTE IMMEDIATE
    'SELECT COUNT(*) FROM ' ||
    DBMS_ASSERT.SIMPLE_SQL_NAME('&&ACTIVE_ARCHIVER_SCHEMA') ||
    '.TBL_ARCHIVER_PARTITIONS@' ||
    DBMS_ASSERT.SIMPLE_SQL_NAME('&&ACTIVE_ARCHIVER_LINK') ||
    ' WHERE 1 = 0'
    INTO l_count;
END;
/

PROMPT REPLICA 002 completed
