PROMPT REPLICA 003 - replica flow

CONNECT &&ACTIVE_REPLICA_SCHEMA/"&&ACTIVE_REPLICA_PASSWORD"@&&ACTIVE_REPLICA_CONNECT

BEGIN
  PKG_REPLICA_RUNNER.prc_run
  (
    p_execute       => 'Y',
    p_stop_after_step => 'PURGE',
    p_purge_execute => 'N'
  );
END;
/

DECLARE
  l_count NUMBER;
  l_total_rows NUMBER := 0;
  l_sql VARCHAR2(4000);
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_PARTITIONS
   WHERE SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
     AND SOURCE_TABLE_NAME IN
         ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
          'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT')
     AND REPLICA_STATUS = 'Y'
     AND QUALITY_STATUS = 'Y'
     AND NVL(SOURCE_ROW_COUNT, -1) = NVL(TARGET_ROW_COUNT, -2)
     AND NVL(TARGET_ROW_COUNT, 0) > 0;

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20600, 'REPLICA flow did not produce any positive quality rows');
  END IF;

  FOR r IN (
    SELECT DISTINCT TARGET_OWNER, TARGET_TABLE_NAME
      FROM TBL_REPLICA_TABLES
     WHERE SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
       AND SOURCE_TABLE_NAME IN
           ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
            'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT')
  ) LOOP
    l_sql := 'SELECT COUNT(*) FROM ' ||
             DBMS_ASSERT.SIMPLE_SQL_NAME(r.TARGET_OWNER) || '.' ||
             DBMS_ASSERT.SIMPLE_SQL_NAME(r.TARGET_TABLE_NAME);
    EXECUTE IMMEDIATE l_sql INTO l_count;
    l_total_rows := l_total_rows + l_count;
  END LOOP;

  IF l_total_rows = 0 THEN
    RAISE_APPLICATION_ERROR(-20601, 'REPLICA targets are empty after replica flow');
  END IF;
END;
/

PROMPT REPLICA 003 completed
