PROMPT REPLICA 004 - quality and invalid objects

CONNECT &&ACTIVE_REPLICA_SCHEMA/"&&ACTIVE_REPLICA_PASSWORD"@&&ACTIVE_REPLICA_CONNECT

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_PARTITIONS
   WHERE SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
     AND SOURCE_TABLE_NAME IN
         ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
          'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT')
     AND REPLICA_STATUS = 'Y'
     AND (QUALITY_STATUS <> 'Y'
          OR NVL(SOURCE_ROW_COUNT, -1) <> NVL(TARGET_ROW_COUNT, -2));

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20610, 'REPLICA quality mismatch rows: ' || l_count);
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM TBL_REPLICA_PARTITIONS
   WHERE SOURCE_OWNER = UPPER('&&ACTIVE_ARCHIVER_SCHEMA')
     AND SOURCE_TABLE_NAME IN
         ('TBL_ARCHIVER_CLIENT1_ORDERS', 'TBL_ARCHIVER_CLIENT1_SUBPART', 'TBL_ARCHIVER_CLIENT1_DAILY_INT',
          'TBL_ARCHIVER_CLIENT2_ORDERS', 'TBL_ARCHIVER_CLIENT2_SUBPART', 'TBL_ARCHIVER_CLIENT2_DAILY_INT')
     AND REPLICA_STATUS = 'Y'
     AND QUALITY_STATUS = 'Y'
     AND PURGE_STATUS = 'N'
     AND NVL(TARGET_ROW_COUNT, 0) > 0;

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20611, 'REPLICA purge preview rows were not found');
  END IF;

  SELECT COUNT(*)
    INTO l_count
    FROM USER_OBJECTS
   WHERE STATUS <> 'VALID';

  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20612, 'REPLICA invalid objects: ' || l_count);
  END IF;
END;
/

PROMPT REPLICA 004 completed
