PROMPT REPLICA 006 - LIST validation and metadata exclusions

CONNECT &&ACTIVE_REPLICA_SCHEMA/"&&ACTIVE_REPLICA_PASSWORD"@&&ACTIVE_REPLICA_CONNECT

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TBL_REPLICA_TEST_TYPE PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TBL_REPLICA_TEST_MULTI PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE TBL_REPLICA_TEST_TYPE
(
  ORDER_DATE VARCHAR2(30) NOT NULL
)
PARTITION BY LIST (ORDER_DATE)
(
  PARTITION P_ERROR VALUES ('#ERROR#')
);

CREATE TABLE TBL_REPLICA_TEST_MULTI
(
  ORDER_DATE DATE NOT NULL,
  ORDER_ID NUMBER NOT NULL
)
PARTITION BY RANGE (ORDER_DATE, ORDER_ID)
(
  PARTITION P_ERROR VALUES LESS THAN (DATE '1800-01-01', 0)
);

DECLARE
  l_count NUMBER;

  PROCEDURE assert_error(p_target VARCHAR2, p_method VARCHAR2, p_code NUMBER) IS
  BEGIN
    BEGIN
      PKG_REPLICA_DISCOVERY.prc_validate_table_setup
      (
        UPPER('&&ACTIVE_ARCHIVER_LINK'), UPPER('&&ACTIVE_ARCHIVER_SCHEMA'),
        'TBL_ARCHIVER_CLIENT1_LIST_DATE', UPPER('&&ACTIVE_REPLICA_SCHEMA'),
        p_target, p_method, NULL
      );
      RAISE_APPLICATION_ERROR(-20650, 'Expected validation error was not raised');
    EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != p_code THEN RAISE; END IF;
    END;
  END;
BEGIN
  assert_error('TBL_REPLICA_CLIENT1_LIST_DATE', 'RANGE', -20264);
  assert_error('TBL_REPLICA_TEST_TYPE', 'LIST', -20266);
  assert_error('TBL_REPLICA_TEST_MULTI', 'LIST', -20262);

  SELECT COUNT(*) INTO l_count
    FROM VW_REPLICA_SOURCE_PARTITIONS
   WHERE SOURCE_TABLE_NAME = 'TBL_ARCHIVER_CLIENT1_ORDERS'
     AND PARTITION_HIGH_VALUE = 'MAXVALUE';
  IF l_count != 1 THEN
    RAISE_APPLICATION_ERROR(-20651, 'MAXVALUE is not visible in REPLICA source metadata');
  END IF;

  SELECT COUNT(*) INTO l_count
    FROM VW_REPLICA_DISCOVERY_PARTITIONS
   WHERE SOURCE_TABLE_NAME = 'TBL_ARCHIVER_CLIENT1_ORDERS'
     AND PARTITION_HIGH_VALUE = 'MAXVALUE';
  IF l_count != 0 THEN
    RAISE_APPLICATION_ERROR(-20652, 'Completed MAXVALUE metadata entered discovery');
  END IF;
END;
/

DROP TABLE TBL_REPLICA_TEST_TYPE PURGE;
DROP TABLE TBL_REPLICA_TEST_MULTI PURGE;

PROMPT REPLICA 006 completed
